// Auto-generated file - DO NOT EDIT
// Generated by scripts/embed_locales.py

#include <string>
#include <unordered_map>

namespace embedded_locales {

const char* en_json = "{\"start\":\"Mouse Jiggler started.\",\"commands\":\"Type 'q' to quit.\",\"exiting\":\"Exiting...\",\"display_error\":\"Failed to open X display\"}";

const std::unordered_map<std::string, const char*> locale_data = {
    {"en", en_json},
};

} // namespace embedded_locales